=== ramom06/Lenguaje-de-marca/Tema4/dtd/ejercicio 2/vecindario/vecindario.dtd
<!ELEMENT comunidad (vecinos+)>
<!ELEMENT vecinos (cod_vecino?, nombre?, apellidos?, portal?, pisoyletra?, cod_cuenta_ord?)>
<!ELEMENT cod_vecino (#PCDATA)>
<!ATTLIST cod_vecino carg (presidente|vicepresidente|secretario|vocal) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre nom CDATA #REQUIRED>
<!ELEMENT apellidos (#PCDATA)>
<!ATTLIST apellidos apel CDATA #REQUIRED>
<!ELEMENT portal (#PCDATA)>
<!ATTLIST portal port CDATA #REQUIRED>
<!ELEMENT pisoyletra (#PCDATA)>
<!ATTLIST pisoyletra piso CDATA #REQUIRED>
<!ELEMENT cod_cuenta_ord (#PCDATA)>
<!ATTLIST cod_cuenta_ord ccc CDATA #REQUIRED>

=== ramom06/Lenguaje-de-marca/Tema4/dtd/ejercicio 2/vecindario/vecindario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comunidad SYSTEM "vecindario.dtd">
<comunidad>
    <vecinos>
        <cod_vecino carg="presidente">001</cod_vecino>
        <nombre nom="Juan"></nombre>
        <apellidos apel="Pérez"></apellidos>
    </vecinos>
    <vecinos>
        <cod_vecino carg="vicepresidente">002</cod_vecino>
        <nombre nom="Ana"></nombre>
        <apellidos apel="García"></apellidos>
        <portal port="B"></portal>
        <pisoyletra piso="2B"></pisoyletra>
    </vecinos>
    <vecinos>
        <cod_vecino carg="secretario">003</cod_vecino>
        <nombre nom="Carlos"></nombre>
        <apellidos apel="Ruiz"></apellidos>
        <portal port="C"></portal>
        <pisoyletra piso="3C"></pisoyletra>
        <cod_cuenta_ord ccc="ES1122334455"></cod_cuenta_ord>
    </vecinos>
    <vecinos>
    </vecinos>
</comunidad>
