=== ramom06/Lenguaje-de-marca/Tema4/dtd/ejercicio 2/biblioteca/biblioteca.dtd
<!ELEMENT biblioteca (libros+)>
<!ELEMENT libros (cod_libro,titulo,editorial,edicion,isbn,num_pag,autor)>
<!ATTLIST libros copia CDATA #IMPLIED>
<!ELEMENT cod_libro (#PCDATA)>
<!ATTLIST cod_libro cod CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ATTLIST editorial editor CDATA #REQUIRED>
<!ELEMENT edicion (#PCDATA)>
<!ATTLIST edicion anio CDATA #REQUIRED>
<!ATTLIST edicion mes CDATA #IMPLIED>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT num_pag (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

=== ramom06/Lenguaje-de-marca/Tema4/dtd/ejercicio 2/biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libros>
        <cod_libro cod="1">123</cod_libro>
        <titulo>Lenguaje de Marcas</titulo>
        <editorial editor="Javier Zurdo">Ra-Ma</editorial>
        <edicion anio="2008">1</edicion>
        <isbn>9876543212</isbn>
        <num_pag>300</num_pag>
        <autor>Pablo Rabasco</autor>
    </libros>
    <libros>
        <cod_libro cod="2">456</cod_libro>
        <titulo>Programaci√≥n</titulo>
        <editorial editor="Juan Carlos Moreno">Ra-Ma</editorial>
        <edicion anio="2009">2</edicion>
        <isbn>987321654</isbn>
        <num_pag>450</num_pag>
        <autor>Laura Raya</autor>
    </libros>
</biblioteca>
